[package]
name = "netty-rust-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
netty-rust-core = { path = "../netty-rust-core" }
tokio.workspace = true
num_cpus.workspace = true
